services:
  # PostgreSQL數據庫
  - type: pserv
    name: calendar-postgres
    runtime: docker
    plan: free
    region: oregon
    image: postgres:15
    envVars:
      - key: POSTGRES_DB
        value: calendar_db
      - key: POSTGRES_USER
        value: calendar_user
      - key: POSTGRES_PASSWORD
        generateValue: true
    
  # Java應用
  - type: web
    name: calendar-task-system
    runtime: docker
    plan: free
    region: oregon
    buildCommand: mvn clean package -DskipTests
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: PORT
        value: 8080
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true
    healthCheckPath: /api/health
    autoDeploy: true
