spring:
  config:
    activate:
      on-profile: production
  
  # 禁用數據庫
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  
  # 服務器配置
server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  
# 日誌配置
logging:
  level:
    root: INFO
    com.taskmanager: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
