spring:
  config:
    activate:
      on-profile: production
  
  # 數據庫配置（暫時使用H2內存數據庫測試）
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # 安全配置（暫時禁用）
  # security:
  #   user:
  #     name: ${ADMIN_USERNAME:admin}
  #     password: ${ADMIN_PASSWORD:admin123}
  
  # 服務器配置
server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
  
# 應用配置
app:
  jwt:
    secret: ${JWT_SECRET:your-secret-key-here}
    expiration: 86400000 # 24小時
  
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
  
# 日誌配置
logging:
  level:
    root: INFO
    com.taskmanager: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
